import '@/styles/main.css';
import '@merzaui/react/dist/theme.css';
import type { Metadata } from 'next';

import NavBar from '@/components/NavBar';
import StyledJsxRegistry from '@/components/providers/StyledJsxRegistry';
import { ThemeProvider } from '@/components/providers/ThemeProvider';

export const metadata: Metadata = {
  title: 'TheUpdate',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='bg-default font-sans text-default antialiased'>
        <ThemeProvider
          attribute='class'
          themes={['light', 'dark-theme']}
          defaultTheme='dark-theme'
          storageKey='merzaui-theme'
          disableTransitionOnChange
        >
          <StyledJsxRegistry>
            <NavBar />
            {children}
          </StyledJsxRegistry>
        </ThemeProvider>
      </body>
    </html>
  );
}
