import type { Metadata } from 'next'
import '@merzaui/react/dist/theme.css'
import '@/styles/main.css'

import { ThemeProvider } from '@/components/ThemeProvider'
import NavBar from '@/components/NavBar'

export const metadata: Metadata = {
  title: 'TheUpdate',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className='bg-default font-sans text-default antialiased'>
        <ThemeProvider
          attribute='class'
          themes={['light', 'dark-theme']}
          defaultTheme='dark-theme'
          enableSystem
          storageKey='merzaui-theme'
          disableTransitionOnChange
        >
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
